// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | TabPanelSlice
  | TextBlockSlice
  | StoreSlice
  | ProgramsCardSlice
  | HeadingAndTextSlice
  | TextAndFormSlice
  | VideoBlockSlice
  | ImageSlice
  | CardsandImagesSlice
  | TextAndImageSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TextBlockSlice
  | HeadingAndTextSlice
  | TextAndFormSlice
  | VideoBlockSlice
  | ImageSlice
  | HeroSlice
  | CardsandImagesSlice
  | TextAndImageSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProgramsDocumentDataSlicesSlice =
  | TextBlockSlice
  | HeadingAndTextSlice
  | TextAndFormSlice
  | VideoBlockSlice
  | ImageSlice
  | HeroSlice
  | CardsandImagesSlice
  | TextAndImageSlice;

/**
 * Content for Programs documents
 */
interface ProgramsDocumentData {
  /**
   * Slice Zone field in *Programs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProgramsDocumentDataSlicesSlice> /**
   * Meta Title field in *Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: programs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: programs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Programs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Programs document from Prismic
 *
 * - **API ID**: `programs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgramsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgramsDocumentData>,
    "programs",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Button field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Newsletter Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.newsletter_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_title: prismic.KeyTextField;

  /**
   * Donate Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.donate_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  donate_title: prismic.KeyTextField;

  /**
   * Donate Body field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.donate_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  donate_body: prismic.RichTextField;

  /**
   * Badge field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.badge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  badge: prismic.ImageField<never>;

  /**
   * Footer Bio field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_bio: prismic.RichTextField;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Documents Link field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.documents_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  documents_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type WhatWeDoDocumentDataSlicesSlice =
  | TextBlockSlice
  | VideoBlockSlice
  | TextAndImageSlice
  | TextAndFormSlice
  | ImageSlice
  | HeroSlice
  | HeadingAndTextSlice
  | CardsandImagesSlice;

/**
 * Content for What we do documents
 */
interface WhatWeDoDocumentData {
  /**
   * Category field in *What we do*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  category: prismic.SelectField<
    | "Programs for Caregivers"
    | "Programs for Children and Youth"
    | "Programs for Schools"
  >;

  /**
   * Featured field in *What we do*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: what_we_do.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  featured: prismic.BooleanField;

  /**
   * Image field in *What we do*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *What we do*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *What we do*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *What we do*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *What we do*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WhatWeDoDocumentDataSlicesSlice> /**
   * Meta Title field in *What we do*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: what_we_do.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *What we do*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: what_we_do.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *What we do*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * What we do document from Prismic
 *
 * - **API ID**: `what_we_do`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhatWeDoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WhatWeDoDocumentData>,
    "what_we_do",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | PageDocument
  | ProgramsDocument
  | SettingsDocument
  | WhatWeDoDocument;

/**
 * Item in *Card → Default → Primary → Card*
 */
export interface CardsandImagesSliceDefaultPrimaryCardItem {
  /**
   * Image field in *Card → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.default.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Card → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.default.primary.card[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Card → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.default.primary.card[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Card → Default → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.default.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bg Color field in *Card → Default → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Dark Blue
   * - **API ID Path**: cardsand_images.default.primary.card[].bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "White", "filled">;
}

/**
 * Item in *Card → Card with icon inside → Primary → Card*
 */
export interface CardsandImagesSliceCardWithIconInsidePrimaryCardItem {
  /**
   * Image field in *Card → Card with icon inside → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Card → Card with icon inside → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Card → Card with icon inside → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Card → Card with icon inside → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bg Color field in *Card → Card with icon inside → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Dark Blue
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[].bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "Yellow", "filled">;
}

/**
 * Item in *Card → Card with icon outside → Primary → Card*
 */
export interface CardsandImagesSliceCardWithIconOutsidePrimaryCardItem {
  /**
   * Image field in *Card → Card with icon outside → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Card → Card with icon outside → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Card → Card with icon outside → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Card → Card with icon outside → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bg Color field in *Card → Card with icon outside → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Dark Blue
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[].bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "Yellow", "filled">;
}

/**
 * Item in *Card → Image Side → Primary → Card*
 */
export interface CardsandImagesSliceImageSidePrimaryCardItem {
  /**
   * Image field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image Direction field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: right
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  direction: prismic.SelectField<"right" | "left", "filled">;

  /**
   * Heading field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Bg Color field in *Card → Image Side → Primary → Card*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Dark Blue
   * - **API ID Path**: cardsand_images.imageSide.primary.card[].bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "White", "filled">;
}

/**
 * Primary content in *Card → Default → Primary*
 */
export interface CardsandImagesSliceDefaultPrimary {
  /**
   * padding field in *Card → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: cardsand_images.default.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding "
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;

  /**
   * Card field in *Card → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardsandImagesSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for Card Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsandImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsandImagesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Card → Card with icon inside → Primary*
 */
export interface CardsandImagesSliceCardWithIconInsidePrimary {
  /**
   * padding field in *Card → Card with icon inside → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding "
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;

  /**
   * Card field in *Card → Card with icon inside → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconInside.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<
    Simplify<CardsandImagesSliceCardWithIconInsidePrimaryCardItem>
  >;
}

/**
 * Card with icon inside variation for Card Slice
 *
 * - **API ID**: `cardWithIconInside`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsandImagesSliceCardWithIconInside =
  prismic.SharedSliceVariation<
    "cardWithIconInside",
    Simplify<CardsandImagesSliceCardWithIconInsidePrimary>,
    never
  >;

/**
 * Primary content in *Card → Card with icon outside → Primary*
 */
export interface CardsandImagesSliceCardWithIconOutsidePrimary {
  /**
   * padding field in *Card → Card with icon outside → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding "
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;

  /**
   * Card field in *Card → Card with icon outside → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.cardWithIconOutside.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<
    Simplify<CardsandImagesSliceCardWithIconOutsidePrimaryCardItem>
  >;
}

/**
 * Card with icon outside variation for Card Slice
 *
 * - **API ID**: `cardWithIconOutside`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsandImagesSliceCardWithIconOutside =
  prismic.SharedSliceVariation<
    "cardWithIconOutside",
    Simplify<CardsandImagesSliceCardWithIconOutsidePrimary>,
    never
  >;

/**
 * Primary content in *Card → Image Side → Primary*
 */
export interface CardsandImagesSliceImageSidePrimary {
  /**
   * padding field in *Card → Image Side → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: cardsand_images.imageSide.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding "
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;

  /**
   * Card field in *Card → Image Side → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cardsand_images.imageSide.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<
    Simplify<CardsandImagesSliceImageSidePrimaryCardItem>
  >;
}

/**
 * Image Side variation for Card Slice
 *
 * - **API ID**: `imageSide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsandImagesSliceImageSide = prismic.SharedSliceVariation<
  "imageSide",
  Simplify<CardsandImagesSliceImageSidePrimary>,
  never
>;

/**
 * Slice variation for *Card*
 */
type CardsandImagesSliceVariation =
  | CardsandImagesSliceDefault
  | CardsandImagesSliceCardWithIconInside
  | CardsandImagesSliceCardWithIconOutside
  | CardsandImagesSliceImageSide;

/**
 * Card Shared Slice
 *
 * - **API ID**: `cardsand_images`
 * - **Description**: CardsandImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsandImagesSlice = prismic.SharedSlice<
  "cardsand_images",
  CardsandImagesSliceVariation
>;

/**
 * Primary content in *HeadingAndText → Default → Primary*
 */
export interface HeadingAndTextSliceDefaultPrimary {
  /**
   * Heading field in *HeadingAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *HeadingAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for HeadingAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeadingAndText → With Links → Primary*
 */
export interface HeadingAndTextSliceWithLinksPrimary {
  /**
   * Heading field in *HeadingAndText → With Links → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.withLinks.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *HeadingAndText → With Links → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.withLinks.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *HeadingAndText → With Links → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_and_text.withLinks.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * With Links variation for HeadingAndText Slice
 *
 * - **API ID**: `withLinks`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingAndTextSliceWithLinks = prismic.SharedSliceVariation<
  "withLinks",
  Simplify<HeadingAndTextSliceWithLinksPrimary>,
  never
>;

/**
 * Slice variation for *HeadingAndText*
 */
type HeadingAndTextSliceVariation =
  | HeadingAndTextSliceDefault
  | HeadingAndTextSliceWithLinks;

/**
 * HeadingAndText Shared Slice
 *
 * - **API ID**: `heading_and_text`
 * - **Description**: HeadingAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingAndTextSlice = prismic.SharedSlice<
  "heading_and_text",
  HeadingAndTextSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Kicker field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.kicker
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  kicker: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: (Optional)
   * - **API ID Path**: hero.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;

  /**
   * Video Platform field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: TikTok
   * - **API ID Path**: hero.default.primary.video_platform
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  video_platform: prismic.SelectField<"TikTok" | "YouTube", "filled">;

  /**
   * Video ID field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_id: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Centered Hero → Primary*
 */
export interface HeroSliceCenteredHeroPrimary {
  /**
   * Heading field in *Hero → Centered Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredHero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Hero → Centered Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.centeredHero.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Hero → Centered Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: (Optional)
   * - **API ID Path**: hero.centeredHero.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;
}

/**
 * Centered Hero variation for Hero Slice
 *
 * - **API ID**: `centeredHero`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceCenteredHero = prismic.SharedSliceVariation<
  "centeredHero",
  Simplify<HeroSliceCenteredHeroPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceCenteredHero;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ImageBlock → Multiple images → Primary → Images*
 */
export interface ImageSliceMultipleImagesPrimaryImagesItem {
  /**
   * Image field in *ImageBlock → Multiple images → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.multipleImages.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Smaller field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image.default.primary.smaller
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  smaller: prismic.BooleanField;

  /**
   * No padding field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image.default.primary.no_padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  no_padding: prismic.BooleanField;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageBlock → Multiple images → Primary*
 */
export interface ImageSliceMultipleImagesPrimary {
  /**
   * Images field in *ImageBlock → Multiple images → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image.multipleImages.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageSliceMultipleImagesPrimaryImagesItem>
  >;

  /**
   * No padding field in *ImageBlock → Multiple images → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image.multipleImages.primary.no_padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  no_padding: prismic.BooleanField;

  /**
   * No gap field in *ImageBlock → Multiple images → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image.multipleImages.primary.no_gap
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  no_gap: prismic.BooleanField;
}

/**
 * Multiple images variation for ImageBlock Slice
 *
 * - **API ID**: `multipleImages`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceMultipleImages = prismic.SharedSliceVariation<
  "multipleImages",
  Simplify<ImageSliceMultipleImagesPrimary>,
  never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceMultipleImages;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Primary content in *ProgramsCard → Default → Primary*
 */
export interface ProgramsCardSliceDefaultPrimary {
  /**
   * padding field in *ProgramsCard → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: programs_card.default.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding"
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;
}

/**
 * Default variation for ProgramsCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgramsCardSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ProgramsCard → imageSide → Primary*
 */
export interface ProgramsCardSliceImageSidePrimary {
  /**
   * padding field in *ProgramsCard → imageSide → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: normal padding
   * - **API ID Path**: programs_card.imageSide.primary.padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  padding: prismic.SelectField<
    | "normal padding "
    | "smaller padding"
    | "no padding"
    | "no top padding"
    | "no bottom padding",
    "filled"
  >;

  /**
   * Image Direction field in *ProgramsCard → imageSide → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: right
   * - **API ID Path**: programs_card.imageSide.primary.image_direction
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  image_direction: prismic.SelectField<"right" | "left", "filled">;
}

/**
 * imageSide variation for ProgramsCard Slice
 *
 * - **API ID**: `imageSide`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsCardSliceImageSide = prismic.SharedSliceVariation<
  "imageSide",
  Simplify<ProgramsCardSliceImageSidePrimary>,
  never
>;

/**
 * Slice variation for *ProgramsCard*
 */
type ProgramsCardSliceVariation =
  | ProgramsCardSliceDefault
  | ProgramsCardSliceImageSide;

/**
 * ProgramsCard Shared Slice
 *
 * - **API ID**: `programs_card`
 * - **Description**: ProgramsCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProgramsCardSlice = prismic.SharedSlice<
  "programs_card",
  ProgramsCardSliceVariation
>;

/**
 * Item in *Store → Default → Primary → Items*
 */
export interface StoreSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *Store → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: store.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Store → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store.default.primary.items[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Store → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: store.default.primary.items[].body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Price field in *Store → Default → Primary → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: store.default.primary.items[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Primary content in *Store → Default → Primary*
 */
export interface StoreSliceDefaultPrimary {
  /**
   * Items field in *Store → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: store.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.GroupField<Simplify<StoreSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Store Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoreSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StoreSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Store*
 */
type StoreSliceVariation = StoreSliceDefault;

/**
 * Store Shared Slice
 *
 * - **API ID**: `store`
 * - **Description**: Store
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoreSlice = prismic.SharedSlice<"store", StoreSliceVariation>;

/**
 * Item in *Tab Panel → Default → Primary → Content*
 */
export interface TabPanelSliceDefaultPrimaryContentItem {
  /**
   * Heading field in *Tab Panel → Default → Primary → Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tab_panel.default.primary.content[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *Tab Panel → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tab_panel.default.primary.content[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Tab Panel → Default → Primary → Content*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: tab_panel.default.primary.content[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *Tab Panel → Default → Primary → Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tab_panel.default.primary.content[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Tab Panel → Default → Primary*
 */
export interface TabPanelSliceDefaultPrimary {
  /**
   * Content field in *Tab Panel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tab_panel.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<TabPanelSliceDefaultPrimaryContentItem>>;
}

/**
 * Default variation for Tab Panel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TabPanelSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Tab Panel*
 */
type TabPanelSliceVariation = TabPanelSliceDefault;

/**
 * Tab Panel Shared Slice
 *
 * - **API ID**: `tab_panel`
 * - **Description**: Tab Panel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TabPanelSlice = prismic.SharedSlice<
  "tab_panel",
  TabPanelSliceVariation
>;

/**
 * Primary content in *TextAndForm → Default → Primary*
 */
export interface TextAndFormSliceDefaultPrimary {
  /**
   * Heading field in *TextAndForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *TextAndForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_form.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Form field in *TextAndForm → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_form.default.primary.form
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  form: prismic.SelectField<"Contact Form" | "Newsletter Form">;

  /**
   * Bg Color field in *TextAndForm → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_form.default.primary.bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "Yellow">;

  /**
   * Bg Color Full Width field in *TextAndForm → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_form.default.primary.bg_color_full_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color_full_width: prismic.SelectField<"Dark Blue" | "Yellow">;
}

/**
 * Default variation for TextAndForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextAndForm*
 */
type TextAndFormSliceVariation = TextAndFormSliceDefault;

/**
 * TextAndForm Shared Slice
 *
 * - **API ID**: `text_and_form`
 * - **Description**: TextAndForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndFormSlice = prismic.SharedSlice<
  "text_and_form",
  TextAndFormSliceVariation
>;

/**
 * Primary content in *TextAndImage → Default → Primary*
 */
export interface TextAndImageSliceDefaultPrimary {
  /**
   * Heading field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;

  /**
   * Bg Color field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: (Optional)
   * - **API ID Path**: text_and_image.default.primary.bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "Yellow">;

  /**
   * Bg Color Full Width field in *TextAndImage → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: (Optional)
   * - **API ID Path**: text_and_image.default.primary.bg_color_full_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color_full_width: prismic.SelectField<"Blue" | "Yellow">;
}

/**
 * Default variation for TextAndImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextAndImageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextAndImage → Image on Left → Primary*
 */
export interface TextAndImageSliceImageOnLeftPrimary {
  /**
   * Image field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.imageOnLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.imageOnLeft.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Body field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.imageOnLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_and_image.imageOnLeft.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;

  /**
   * Bg Color field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: (Optional)
   * - **API ID Path**: text_and_image.imageOnLeft.primary.bg_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color: prismic.SelectField<"Dark Blue" | "Yellow">;

  /**
   * Bg Color Full Width field in *TextAndImage → Image on Left → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: (Optional)
   * - **API ID Path**: text_and_image.imageOnLeft.primary.bg_color_full_width
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bg_color_full_width: prismic.SelectField<"Dark Blue" | "Yellow">;
}

/**
 * Image on Left variation for TextAndImage Slice
 *
 * - **API ID**: `imageOnLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSliceImageOnLeft = prismic.SharedSliceVariation<
  "imageOnLeft",
  Simplify<TextAndImageSliceImageOnLeftPrimary>,
  never
>;

/**
 * Slice variation for *TextAndImage*
 */
type TextAndImageSliceVariation =
  | TextAndImageSliceDefault
  | TextAndImageSliceImageOnLeft;

/**
 * TextAndImage Shared Slice
 *
 * - **API ID**: `text_and_image`
 * - **Description**: TextAndImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextAndImageSlice = prismic.SharedSlice<
  "text_and_image",
  TextAndImageSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Body field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * Youtube Video ID field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.youtube_video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtube_video_id: prismic.KeyTextField;

  /**
   * smaller field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_block.default.primary.smaller
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  smaller: prismic.BooleanField;

  /**
   * No padding field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_block.default.primary.no_padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  no_padding: prismic.BooleanField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProgramsDocument,
      ProgramsDocumentData,
      ProgramsDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      WhatWeDoDocument,
      WhatWeDoDocumentData,
      WhatWeDoDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardsandImagesSlice,
      CardsandImagesSliceDefaultPrimaryCardItem,
      CardsandImagesSliceDefaultPrimary,
      CardsandImagesSliceCardWithIconInsidePrimaryCardItem,
      CardsandImagesSliceCardWithIconInsidePrimary,
      CardsandImagesSliceCardWithIconOutsidePrimaryCardItem,
      CardsandImagesSliceCardWithIconOutsidePrimary,
      CardsandImagesSliceImageSidePrimaryCardItem,
      CardsandImagesSliceImageSidePrimary,
      CardsandImagesSliceVariation,
      CardsandImagesSliceDefault,
      CardsandImagesSliceCardWithIconInside,
      CardsandImagesSliceCardWithIconOutside,
      CardsandImagesSliceImageSide,
      HeadingAndTextSlice,
      HeadingAndTextSliceDefaultPrimary,
      HeadingAndTextSliceWithLinksPrimary,
      HeadingAndTextSliceVariation,
      HeadingAndTextSliceDefault,
      HeadingAndTextSliceWithLinks,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceCenteredHeroPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceCenteredHero,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceMultipleImagesPrimaryImagesItem,
      ImageSliceMultipleImagesPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceMultipleImages,
      ProgramsCardSlice,
      ProgramsCardSliceDefaultPrimary,
      ProgramsCardSliceImageSidePrimary,
      ProgramsCardSliceVariation,
      ProgramsCardSliceDefault,
      ProgramsCardSliceImageSide,
      StoreSlice,
      StoreSliceDefaultPrimaryItemsItem,
      StoreSliceDefaultPrimary,
      StoreSliceVariation,
      StoreSliceDefault,
      TabPanelSlice,
      TabPanelSliceDefaultPrimaryContentItem,
      TabPanelSliceDefaultPrimary,
      TabPanelSliceVariation,
      TabPanelSliceDefault,
      TextAndFormSlice,
      TextAndFormSliceDefaultPrimary,
      TextAndFormSliceVariation,
      TextAndFormSliceDefault,
      TextAndImageSlice,
      TextAndImageSliceDefaultPrimary,
      TextAndImageSliceImageOnLeftPrimary,
      TextAndImageSliceVariation,
      TextAndImageSliceDefault,
      TextAndImageSliceImageOnLeft,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
